version: '3'

services:

  redis:
    image: redis:alpine
#    ports:
#      - "6379:6379"

  report:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.docker
    command: sh -c "uvicorn services.report_fastapi:app --host 0.0.0.0 --port 8000"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.docker
    depends_on:
      - postgres
      - redis
    command: python src/bot/app.py

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: financial_records
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5432:5432"
    volumes:
      - app_db:/var/lib/postgresql/data

volumes:
  app_db:
